<?xml version="1.0" encoding="UTF-8"?>

<!--
  Generate a Musical MIDI Accompaniment (MMA) script for a given groove.
-->

<xsl:stylesheet
  version="3.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:mma="http://www.mellowood.ca/mma"
  xmlns:musicxml="http://www.w3.org/2021/06/musicxml40"
  xmlns:map="http://www.w3.org/2005/xpath-functions/map"
  xmlns:array="http://www.w3.org/2005/xpath-functions/array"
  exclude-result-prefixes="#all"
>

  <xsl:output method="text" media-type="text/plain" omit-xml-declaration="yes"/>

  <!--
    User-defined arguments.
  -->
  <xsl:param name="groove" required="yes"/>
  <xsl:param name="chords" select="'z'"/>
  <xsl:param name="tempo" select="120"/>
  <xsl:param name="count" select="4"/>
  <xsl:param name="keysig" select="'C'"/>

  <xsl:template name="groove">
    <xsl:text>
MidiText Generated by github.com/infojunkie/musicxml-midi
KeySig </xsl:text><xsl:value-of select="$keysig"/><xsl:text>
Tempo </xsl:text><xsl:value-of select="$tempo"/><xsl:text>
Groove </xsl:text><xsl:value-of select="$groove"/><xsl:text>
MidiMark Groove:</xsl:text><xsl:value-of select="$groove"/><xsl:text>
Set Duration $( round( $_Time * 60000 / $_Tempo ) )
    </xsl:text>
    <xsl:variable name="chordSeq" select="fn:tokenize($chords, '\s*,\s*')"/>
    <xsl:call-template name="measure">
      <xsl:with-param name="i" select="0"/>
      <xsl:with-param name="count" select="$count"/>
      <xsl:with-param name="chordSeq" select="$chordSeq"/>
    </xsl:call-template>
  </xsl:template>

  <xsl:template name="measure">
    <xsl:param name="i"/>
    <xsl:param name="count"/>
    <xsl:param name="chordSeq"/>
    <xsl:if test="$i &lt; $count">
      <xsl:text>
MidiMark 0 Measure:</xsl:text><xsl:value-of select="$i"/><xsl:text>: $Duration
</xsl:text><xsl:value-of select="$chordSeq[1 + ($i mod count($chordSeq))]"/>
      <xsl:call-template name="measure">
        <xsl:with-param name="i" select="$i+1"/>
        <xsl:with-param name="count" select="$count"/>
        <xsl:with-param name="chordSeq" select="$chordSeq"/>
      </xsl:call-template>
    </xsl:if>
  </xsl:template>

</xsl:stylesheet>
